version: '3.8'

services:
  messaging_backend:
    container_name: oneroute-messaging
    image: oneroute-messaging:0.0.2
    build:
      context: .
    ports:
      - "1112:1112"
    environment:
      - PORT=1112
      - NODE_ENV=development