version: '3.8'

services:
  app:
    container_name: messaging_api
    image: oneroute-messaging:0.0.3
    build:
      context: .
    ports:
      - "1112:1112"
    environment:
      - PORT=1112
      - NODE_ENV=development
      - DATABASE=oneroute-messaging_db
      - DB_USERNAME=postgres
      - PASSWORD=alao1996
      - PG_HOST=database
    depends_on:
      - database
  database:
    container_name: messaging_db
    image: "postgres:12"
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=alao1996
        - POSTGRES_DB=oneroute-messaging_db
    volumes:
        - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}