version: "3.8"
services:
  db:
    container_name: database_application
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=alao1996
      - POSTGRES_DB=oneroute-messaging_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Uncomment if you want to load schema before migrations or any declarations
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    tty: true
    ports:
      - "5432:5432"
  web:
    container_name: web_sample_application
    image: oneroute-messaging:0.0.4
    build:
      context: .
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "1112:1112"
      - "127.0.0.1:9223:9223"
    environment:
      - PORT=1112
      - NODE_ENV=development
      - DATABASE=oneroute-messaging_db
      - DB_USERNAME=postgres
      - PASSWORD=alao1996
      - HOST=database_application
    command: npm run start
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:5432",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - db
    depends_on:
      - db
    env_file: ./.env
    environment:
      - HOST=database_application
volumes:
  pg_data: null