version: '3.8'

services:
  messaging_backend:
    container_name: oneroute-messaging
    image: oneroute-messaging:0.0.3
    build:
      context: .
    ports:
      - "1112:1112"
    environment:
      - PORT=1112
      - NODE_ENV=development
      - DATABASE=oneroute-messaging_db
      - DB_USERNAME=postgres
      - PASSWORD=alao1996
      - PG_HOST=messaging_db
    depends_on:
      - messaging_db
  messaging_db:
    container_name: messaging_db
    image: "postgres:12"
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=Abiodun
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=oneroute-messaging_db
    volumes:
        - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}